# Generated by Django 3.2.4 on 2024-07-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apo', '0004_auto_20240629_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='driving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apo.recurrence'),
        ),
    ]
