# Generated by Django 3.2.4 on 2024-08-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apo', '0007_auto_20240810_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
