# Generated by Django 3.2.4 on 2024-08-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apo', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
